// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Commit = {
    change_id: string;
    commit_id: string;
    author_email: string;
    timestamp: string;
    parents: Array<string>;
    is_immutable: boolean;
    is_conflict: boolean;
    description: string;
    bookmarks: string;
    tags: string;
    is_working_copy: boolean;
};
